### PR TITLE
SNMPDao to support mssql

### PR DESCRIPTION
**Pull request by fxagung**
Hi Thomas,

Please review the changes which are intended to making SNMPDao supporting MSSQL. 
The focus is on adding mssql libraries and updating the CMakeLists.txt to support the compilation options of mysql and mssql (cmake -Ddatabase=mssql ..). The underlying unit test will be fixed separately.

Thank you.

Regards,
Agung

### CODE REVIEW

**Review by mitrais-cdc-cpp — CHANGES_REQUESTED** [review]
pls remove staged temp files, my browser cant handle that much changes while diff inside github :)

**Comment by fxagung** [comment]
Hi Thomas,

I just added a new unit test of SNMPDao which is accessing MSSQL database. Please also review it. Thank you.

Ref: [https://github.com/mitrais-cdc-cpp/SNMPDao/commit/4c6e15a07c4439cb68c8ae63d98df7a641c283b0]

Regards,
Agung

**Comment by fxagung** [comment]
Hi Thomas,

Regarding to your comment of "pls remove staged temp files, my browser cant handle that much changes while diff inside github :)", so far I don't find any temp (.tmp or .temp) content within the pushed modification. Perhaps, the addition of odb-mssql and unix-odbc libraries into the /env folder makes the tracked-changes are so many. But however, beyond that libraries addition, my change was only about CMakeLists.txt file to support multiple databases (mysql and mssql) compilation. 

Please assist me on how to minimize that modification history so you can see them easily. Thank you

Regards,
Agung

**Comment by fxagung** [comment]
Hi Thomas,

the inc/odb_gen has been removed. [odb_gen removed](https://github.com/mitrais-cdc-cpp/SNMPDao/commit/0da51820bf77689511e1cf5e0c46410fb9973b09)

Regards,
Agung

**Comment by mitrais-cdc-cpp** [comment]
have to be reviewed after merge,.. my brower crashes with 19.000 additional line :)

**Pull request merged**
